param(
  [switch]$IncludeUpcoming,
  [switch]$IncludeSingles,
  [switch]$IncludeCvExcluded,
  [switch]$IncludeNonMainAuthor,
  [switch]$SkipPdfBuild,
  [switch]$SkipPressPackage
)

$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$cvDir = Join-Path $root "cv"
$mainTexPath = Join-Path $cvDir "main.tex"
$jsonPath = Join-Path $root "assets\releases.json"
$generatedDir = Join-Path $cvDir "generated"
$generatedTexPath = Join-Path $generatedDir "releases.tex"
$publicCvPath = Join-Path $root "assets\CV_2026.pdf"
$pressPackageScript = Join-Path $root "build-press-package.ps1"
$dateCulture = [System.Globalization.CultureInfo]::GetCultureInfo("en-US")

function Read-Utf8Text($Path) {
  return [System.IO.File]::ReadAllText($Path, [System.Text.Encoding]::UTF8)
}

function Write-Utf8Text($Path, $Text) {
  $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($Path, $Text, $utf8NoBom)
}

function Escape-Latex($Value) {
  $text = [string]$Value
  if ([string]::IsNullOrWhiteSpace($text)) {
    return "---"
  }

  $text = $text.Trim()
  $text = $text -replace '\\', '\textbackslash{}'
  $text = $text -replace '&', '\&'
  $text = $text -replace '%', '\%'
  $text = $text -replace '\$', '\$'
  $text = $text -replace '#', '\#'
  $text = $text -replace '_', '\_'
  $text = $text -replace '\{', '\{'
  $text = $text -replace '\}', '\}'
  $text = $text -replace '\^', '\textasciicircum{}'
  $text = $text -replace '~', '\textasciitilde{}'
  $text = $text -replace '—', '--'
  $text = $text -replace '–', '--'
  return $text
}

function Format-CvDate($Item) {
  $start = [datetime]::ParseExact($Item.date, "yyyy-MM-dd", $null)
  if ($Item.dateEnd) {
    $end = [datetime]::ParseExact($Item.dateEnd, "yyyy-MM-dd", $null)
    if ($start.Year -eq $end.Year -and $start.Month -eq $end.Month) {
      return ("{0}--{1}" -f $start.ToString("dd", $dateCulture), $end.ToString("dd MMM yyyy", $dateCulture))
    }
    if ($start.Year -eq $end.Year) {
      return ("{0}--{1}" -f $start.ToString("dd MMM", $dateCulture), $end.ToString("dd MMM yyyy", $dateCulture))
    }
    return ("{0}--{1}" -f $start.ToString("dd MMM yyyy", $dateCulture), $end.ToString("dd MMM yyyy", $dateCulture))
  }

  return $start.ToString("dd MMM yyyy", $dateCulture)
}

function Get-CollaboratorText($Collaborators) {
  if (-not $Collaborators) {
    return ""
  }

  $names = @()
  foreach ($collaborator in $Collaborators) {
    if ($collaborator -is [string]) {
      if (-not [string]::IsNullOrWhiteSpace($collaborator)) {
        $names += $collaborator.Trim()
      }
    } elseif ($collaborator.name) {
      $name = [string]$collaborator.name
      if ($collaborator.role) {
        $name = "$name ($($collaborator.role))"
      }
      $names += $name.Trim()
    }
  }

  if ($names.Count -eq 0) {
    return ""
  }

  return "w/ " + ($names -join ", ")
}

function Format-Place($Item) {
  $parts = @()
  if ($Item.city) {
    $parts += [string]$Item.city
  }
  if ($Item.venue) {
    $parts += [string]$Item.venue
  }
  if ($parts.Count -eq 0 -and $Item.country) {
    $parts += [string]$Item.country
  }
  if ($parts.Count -eq 0) {
    return "---"
  }
  return $parts -join " -- "
}

function Patch-MainTexInput {
  $mainTex = Read-Utf8Text $mainTexPath
  if ($mainTex -match '\\input\{generated/releases\.tex\}') {
    return
  }

  $pattern = '(?s)\{\\footnotesize\s*\\begin\{tabularx\}\{\\textwidth\}.*?\\end\{tabularx\}\s*\}'
  $replacement = "{\footnotesize`r`n\input{generated/releases.tex}`r`n}"
  $patched = [regex]::Replace($mainTex, $pattern, $replacement, 1)

  if ($patched -eq $mainTex) {
    throw "Could not find the hard-coded CV releases table in cv/main.tex."
  }

  Write-Utf8Text $mainTexPath $patched
}

if (-not (Test-Path -LiteralPath $mainTexPath -PathType Leaf)) {
  throw "Missing LaTeX CV source: $mainTexPath"
}
if (-not (Test-Path -LiteralPath $jsonPath -PathType Leaf)) {
  throw "Missing releases JSON: $jsonPath"
}

$releases = Read-Utf8Text $jsonPath | ConvertFrom-Json
$items = $releases | Where-Object {
  $cvAuthorRole = if ($_.cvAuthorRole) { [string]$_.cvAuthorRole } else { "" }
  $isMainAuthor = $_.cvMainAuthor -ne $false -and $cvAuthorRole -notmatch '^(support|collaborator|performer|accompaniment)$'

  ($IncludeUpcoming -or $_.status -ne "upcoming") -and
  ($IncludeSingles -or $_.type -ne "single") -and
  ($IncludeCvExcluded -or $_.cv -ne $false) -and
  ($IncludeNonMainAuthor -or $isMainAuthor)
} | Sort-Object @{ Expression = { [datetime]::ParseExact($_.date, "yyyy-MM-dd", $null) }; Descending = $true }

if (-not (Test-Path -LiteralPath $generatedDir -PathType Container)) {
  New-Item -ItemType Directory -Path $generatedDir | Out-Null
}

$lines = @()
$lines += "% Auto-generated by build-cv-from-releases.ps1 from assets/releases.json."
$lines += "% Edit assets/releases.json, then rebuild. Do not edit this file by hand."
$lines += "\begin{tabularx}{\textwidth}{@{}p{0.12\textwidth}p{0.18\textwidth}Y p{0.18\textwidth} p{0.18\textwidth}@{}}"
$lines += "\textbf{Date} & \textbf{Event / Series} & \textbf{Piece / Work} & \textbf{Role} & \textbf{Place} \\"
$lines += "\hline"
$lines += ""

foreach ($item in $items) {
  $date = Escape-Latex (Format-CvDate $item)
  $event = Escape-Latex $(if ($item.event) { $item.event } else { "---" })
  $title = Escape-Latex $(if ($item.title) { $item.title } else { "---" })
  $role = Escape-Latex $(if ($item.format) { $item.format } elseif ($item.type) { $item.type } else { "---" })
  $place = Escape-Latex (Format-Place $item)
  $noteParts = @()

  $collaborators = Get-CollaboratorText $item.collaborators
  if ($collaborators) {
    $noteParts += $collaborators
  }
  if ($item.context) {
    $noteParts += [string]$item.context
  }
  if ($item.status -eq "upcoming") {
    $noteParts += "upcoming"
  }

  if ($noteParts.Count -gt 0) {
    $lines += "$date & $event & \textit{$title} & $role & $place \\"
    $note = Escape-Latex ($noteParts -join "; ")
    $lines += "\multicolumn{5}{@{}p{\textwidth}@{}}{\scriptsize $note} \\[0.25em]"
  } else {
    $lines += "$date & $event & \textit{$title} & $role & $place \\[0.25em]"
  }
  $lines += ""
}

$lines += "\end{tabularx}"
Write-Utf8Text $generatedTexPath ($lines -join "`r`n")
Patch-MainTexInput

Write-Host "Generated $generatedTexPath from $($items.Count) JSON item(s)."

if (-not $SkipPdfBuild) {
  Push-Location $cvDir
  try {
    latexmk -pdf -interaction=nonstopmode -halt-on-error main.tex
    if ($LASTEXITCODE -ne 0) {
      throw "latexmk failed with exit code $LASTEXITCODE"
    }
  } finally {
    Pop-Location
  }

  $builtPdf = Join-Path $cvDir "main.pdf"
  if (-not (Test-Path -LiteralPath $builtPdf -PathType Leaf)) {
    throw "LaTeX build finished without producing $builtPdf"
  }

  Copy-Item -LiteralPath $builtPdf -Destination $publicCvPath -Force
  Write-Host "Updated $publicCvPath"
}

if (-not $SkipPressPackage -and (Test-Path -LiteralPath $pressPackageScript -PathType Leaf)) {
  & powershell -NoProfile -ExecutionPolicy Bypass -File $pressPackageScript
}
